### ISSUE TITLE
[issue] empty screen space below keyboard

### ISSUE THREAD

**Issue by lgasp** [AnySoftKeyboard/AnySoftKeyboard#1955]
### Steps to reproduce
1. Use AnySoftKeyboard on a device without on screen android soft buttons
2. Happens with ASK version 1.10.1093 from google play store. Previous version was ok
3.when android soft buttons are on screen, they are in correct position, below keyboard

### Expected behaviour
No empty screen space below lower keyboard line ( the one with spacebar).

### Actual behaviour
There is an empty unused space below keyboard.

**Android OS version:**
8.1.0

**Device manufacturer and model:**
Motorola Moto G5S
**List of installed add-ons (like languages, or themes):**
No addons

![Screenshot_20200111-143820~3](https://user-images.githubusercontent.com/3661279/72205316-fab7da80-3481-11ea-91e8-63865ebece84.png)

**Comment by menny** [comment]
which kind of navigation bar (back, home, recent keys) are you using? Do you have hardware keys? Or is it on-screen navigation?

**Comment by lgasp** [comment]
Navigation is done with the fingerprint sensor, below the screen

**Comment by cliffliang** [comment]
I see the same with the latest version. I hide the nav bar with the Magisk Module, "Hide Navigation Bar" and use LMT for navigation.

**Comment by menny** [comment]
What's LMT?

**Comment by cliffliang** [comment]
It's like pie control. 

https://forum.xda-developers.com/showthread.php?t=1330150

**Comment by danielbouman** [comment]
I have the same issue on a Oneplus 5T, Android 9. For navigation I use gestures, so there is no navigation bar. When I turn the navigation bar on, it replaces the empty space.

**Comment by menny** [comment]
for now, this is fixed. We'll have another issue open for the next release.

**Comment by vikaig** [comment]
Same
Xiaomi Redmi Note 4Х(mido)
LineageOS 16.0(Android Pie 9.0)
AnySoftKeyboard Version 1.10.1109, version-code 6279 from F-Droid
![q](https://user-images.githubusercontent.com/50102214/85193494-c4ed0c80-b2d1-11ea-8183-6b8c1e33af20.png)

**Comment by menny** [comment]
@vikaig what kind of navigation does your device use?

**Comment by vikaig** [comment]
@menny hardware https://i1.rozetka.ua/goods/2043549/xiaomi_redmi_note4x_3_32_gld_eu_images_2043549276.jpg

**Comment by wertzuz** [comment]
this is not fixed i have the issue on a motorola device. when you set navigation bar to hidden there is a transpartent space below the keyboard. any update on this?
