### ISSUE TITLE
[Bug] [Android 10] - crash when pressing emoji button

### ISSUE THREAD

**Issue by IbraheemEhab** [AnySoftKeyboard/AnySoftKeyboard#2375]
### Steps to reproduce
1.Nothing just every day 2-3 times it happens espicially when long press the emoji button

### Actual behaviour
The keyboard freezes and the android gives me this qoutes “android developer warning failed to post notification on channel "null" please contact developer” and it makes the device completely frozen not even able to shut it down or something until the screen timeout reached and the system tells me if I want to shut the app down

**Android OS version:**
10
**Device manufacturer and model:**
Samsung A51
**List of installed add-ons (like languages, or themes):**
Arabic, English, ancient languages pack

**Comment by menny** [comment]
thanks for reporting.

Which version of AnySoftKeyboard do you use?
You mentioned that this crash happens when long-pressing. Can you try to pin-point when? Specific languages? Specific apps?

**Comment by IbrahimEhabElSayed** [comment]
> thanks for reporting.
> 
> Which version of AnySoftKeyboard do you use?
> You mentioned that this crash happens when long-pressing. Can you try to pin-point when? Specific languages? Specific apps?

I used the regular latest version on google play but when it didn’t help i used the latest beta 1.10.1514 and it even frozen inside the settings app !! So until the ltest version it still happens.
No it happens like everywhere, in whatsapp,messenger, android settings and from an hour ago when i tried to tweak some setting the app frozen and gave me the same warning about failing to post notification in channel null... so It’s not so clear why this happens and when exactly. I use arabic a lot but it did happened in english also "and I don.t know why 70% of the times it happened because of long pressing emoji button"

**Comment by menny** [comment]
Do any of you have access to `logcat`? I fail to find the issue.

**Comment by CyanusBird** [comment]
unfortunately the issue is still persistent until even the lastest beta, just tell me how to find the logcat and produce it because even this issue is very frustrating, I DO love this keyboard and can't stop using it.

**Comment by menny** [comment]
Option one:
You'll need to install ADB, which is part of the Android SDK.
See here:
https://www.google.com/search?q=install+android+adb&oq=install+android+adb&aqs=chrome..69i57j0l4.6297j0j4&sourceid=chrome-mobile&ie=UTF-8

After that, enable debugging on your device, and connect it to your
computer using a USB cable.

If all goes well, you will need to run "adb logcat"
This will print out the device logs.


Another option, is to allow Debug Reporting in the power menu, reproduce
the crash and then generate the debug report:
https://developer.android.com/studio/debug/bug-report

**Comment by CyanusBird** [comment]
I tried bug reporter in developer options with full report option beeing selected, if you kindly can tell me if that worked I will be very happy
[dumpstate-2020-11-10-19-36-02.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5519430/dumpstate-2020-11-10-19-36-02.zip)

**Comment by menny** [comment]
I might have found the issue, but I'm not sure. Would you mind try our a debug version with the possible fix?

**Comment by menny** [comment]
Please, download the APK from https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1483242743/artifacts/25688190
and install it on your device.

To be able to go back to the latest stable version:

1. Backup settings in AnySoftKeyboard
1. uninstall
1. download, unzip and install the APK from the link
1. follow the setup process
1. restore from the previously saved backup file.
1. Verify that everything is good.

Note: Keeping this version will not allow auto-updates from Google Play Store.

if you want to go back to the previous stable version:

1. Uninstall the test version
1. Install AnySoftKeyboard from Play Store
1. Follow the setup process.
1. restore from the previously saved backup file

**Comment by menny** [comment]
@CyanusBird, if the keyboard crashes for you again, please generate another debug report and attach it here.

Thank you!

**Comment by CyanusBird** [comment]
Thanks for your work, you really an awsome man, I'll try and tell you if the problem is the same again

**Comment by CyanusBird** [comment]
unfortunately it happened again few minutes ago after nearly a day of use, I immediately make a report after the crash with few seconds and I hope you can find where is the problem.
[dumpstate-2020-11-11-21-17-27.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5526258/dumpstate-2020-11-11-21-17-27.zip)

**Comment by menny** [comment]
I didn't get enough information as I hoped for.
Would you mind installing a debug version? It is very similar to the one you already have install, but has much more logging.

If you do install this version, please remove it after you get a crash and generate a report.
[ime-app-1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5527631/ime-app-1.zip)

**Comment by kurdikeyboard** [comment]
> I didn't get enough information as I hoped for.
> Would you mind installing a debug version? It is very similar to the one you already have install, but has much more logging.
> 
> If you do install this version, please remove it after you get a crash and generate a report.
> [ime-app-1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5527631/ime-app-1.zip)

The freezes is still not fixed after some usage of the keyboard when you press emoji key the app frozen and every time clear app data and cache to fix that freeze on screen keyboard!

**Comment by menny** [comment]
@kurdikeyboard  I am not able to reproduce this freeze and crash. I use Android 10 and Android 11.
Would you mind trying out the version at https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5527631/ime-app-1.zip and if it crashes for you, please generate a bug report and send over here.

**Comment by CyanusBird** [comment]
I used th debug version for another day and after the keyboard freezed again I waited for 5 minutes and generated a full report as usual from developer mode option. hope that will find a solution as it turns out that I'm not the only one with the same problem; it could be because of the samsung? I don't know... I have an android 6,7 and it didn't happen on those phones
[dumpstate-2020-11-13-22-38-19.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5539312/dumpstate-2020-11-13-22-38-19.zip)

**Comment by kurdikeyboard** [comment]
> @kurdikeyboard I am not able to reproduce this freeze and crash. I use Android 10 and Android 11.
> Would you mind trying out the version at https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5527631/ime-app-1.zip and if it crashes for you, please generate a bug report and send over here.

Finally! The suddenly freezing problem was fixed for me this one https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5527631/ime-app-1.zip doesn't have any freezing issues on my device i used it for more than 30 minutes continuously and the app worked like a charm even with Gestures typing enabled :) 

After one year my biggest problem with freeze was fixed from Nov 2019 to Nov 2020 (^_^)

Thank you so much for your hard and great works dude you are awesome ;) 

Device: Xiaomi Mi 9T Pro (aka Redmi K20 Pro)

OS version: Android 10 with MIUI 12.3 by xiaomi.eu 20.11.11 Beta

**Comment by kurdikeyboard** [comment]
> I used th debug version for another day and after the keyboard freezed again I waited for 5 minutes and generated a full report as usual from developer mode option. hope that will find a solution as it turns out that I'm not the only one with the same problem; it could be because of the samsung? I don't know... I have an android 6,7 and it didn't happen on those phones
> [dumpstate-2020-11-13-22-38-19.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5539312/dumpstate-2020-11-13-22-38-19.zip)

Hey! try to use that one attached below i think the freeze issuses was fixed i used on my Android 10 device without any freezing :) 

Try this: https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5527631/ime-app-1.zip

**Comment by CyanusBird** [comment]
> n as

Ok I'll try it again, hope to work :)

**Comment by CyanusBird** [comment]
@kurdikeyboard 
Ok I'll try this one

**Comment by CyanusBird** [comment]
I think it's the same debug version that i used and also generated the last bug report on it and posted it here, unfortunately it didn't solve the weird freezing...

**Comment by menny** [comment]
I think that I found the issue: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2551

**Comment by menny** [comment]
I will need you to verify the fix:
[ime-app-1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5541782/ime-app-1.zip)

**Comment by kurdikeyboard** [comment]
> I will need you to verify the fix:
> [ime-app-1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5541782/ime-app-1.zip)

DONE! the freezing and suddnley jamed problem was fixed on android 10 with this debug version i hope you added to the Beta ot Stable channel soon :)

**Comment by CyanusBird** [comment]
> 
> 
> I will need you to verify the fix:
> [ime-app-1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5541782/ime-app-1.zip)
i used that version and again it freezes, I don't know why but i produced another bug report, hope that there is something
[dumpstate-2020-11-23-12-47-32.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5582395/dumpstate-2020-11-23-12-47-32.zip)

**Comment by kurdikeyboard** [comment]
> > I will need you to verify the fix:
> > [ime-app-1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5541782/ime-app-1.zip)
> 
> i used that version and again it freezes, I don't know why but i produced another bug report, hope that there is something
> [dumpstate-2020-11-23-12-47-32.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5582395/dumpstate-2020-11-23-12-47-32.zip)

Yeah sadly you right after a month a got freeze again with latest Beta relaease version :( 

Device: Mi 9T Pro

System: Stock Android 10 with stable MIUI 12 version

**Comment by CyanusBird** [comment]
> > > I will need you to verify the fix:
> > > [ime-app-1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5541782/ime-app-1.zip)
> > 
> > 
> > i used that version and again it freezes, I don't know why but i produced another bug report, hope that there is something
> > [dumpstate-2020-11-23-12-47-32.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5582395/dumpstate-2020-11-23-12-47-32.zip)
> 
> Yeah sadly you right after a month a got freeze again with latest Beta relaease version :(
> 
> Device: Mi 9T Pro
> 
> System: Stock Android 10 rom with stable MIUI 12 version

I found something maybe could help...
I have a Sony z5 premium mobile with the same version of anysoftkeyboard and android 7, every time I update my keyboard it gives me a notification that to be careful as I'm using an experimental version, when i update my keyboard on Samsung it immediately gives me that message of failed to post notification on channel null and it doesn't show any kind of notification just as my Sony phone. and of course after a while of using it freezes.
hope that help
@menny

**Comment by menny** [comment]
Can someone generate a bug-report?
Please use this version:
[a.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5880991/a.zip)

**Comment by menny** [comment]
I want to release a new version in a few days, please provide the debug logs.

**Comment by CyanusBird** [comment]
> I want to release a new version in a few days, please provide the debug logs.

Ok I'll install the debug version now and wait for the freeze to happen and upload it again, I just hoped that the other user could do that because I have uploaded the report two times before with no result

**Comment by menny** [comment]
sorry about that.

**Comment by CyanusBird** [comment]
How to print out the ADB logcat from cmd ?? 
@menny

**Comment by menny** [comment]
Not super hard, just a bunch of steps: https://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat

**Comment by CyanusBird** [comment]
> Not super hard, just a bunch of steps: https://android.stackexchange.com/a/33217

Here My logcat
and my bug report from developer options
[Anysoftkeyboard.txt](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5904449/Anysoftkeyboard.txt)
[dumpstate-2021-02-01-16-21-54.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5904478/dumpstate-2021-02-01-16-21-54.zip)

**Comment by menny** [comment]
@CyanusBird did you get a crash?

**Comment by CyanusBird** [comment]
> @CyanusBird did you get a crash?

I do get the messege

**Comment by menny** [comment]
And you generated the logcat _after_ getting the error? Please reproduce that again. To make sure we have the right log

**Comment by CyanusBird** [comment]
> And you generated the logcat _after_ getting the error? Please reproduce that again. To make sure we have the right log

I tried to reproduce the crash as I'm in the logcat. but that was hard because the crash is happening with no certain action except the long pressing on the emoji or even now any long press on any other key, and that's is something with no prediction that I can know, I tried hard those past two days to make it crash while I logcat it but it crashes when I no longer connected with computer. sorry about that I really really tried but with no success. hope that when my phone complete update to android 11 in late march that all that problems would be solved somehow... and thanks for your amazing communication 💙

**Comment by menny** [comment]
sure, I understand. In any case, if you are able to produce a debug report immediately after a crash, please attach it here.

**Comment by CyanusBird** [comment]
Hi, so I finally took some time after I relly get tired of the annoying freeze and connected my phone to adb as mentioned above and after a while I finally reproduced the bug and extracted it's logcat and I copy it into this txt file
[logcat.txt](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/6600080/logcat.txt)
and also generated a logcat inside the app here it is
Hi! Here is a LogCat snippet for AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.10.1794 release 6964. Installed on 0, first release installed was 6266.
BRAND:samsung
DEVICE:a51
Build ID:RP1A.200720.012.A515FXXU4EUD7
changelist number:RP1A.200720.012
MODEL:SM-A515F
PRODUCT:a51nsxx
TAGS:release-keys
VERSION.INCREMENTAL:A515FXXU4EUD7
VERSION.RELEASE:11
VERSION.SDK_INT:30
Locale:en_GB
configuration:{1.1 602mcc2mnc [en_GB] ldltr sw360dp w360dp h770dp 480dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 88 - 1080, 2400) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} s.1 bts=0 ff=0 bf=1 themeSeq=0}
That's all I know.
Log contains 0 lines:

**Comment by CyanusBird** [comment]
And also I generated a bug report after the crash by developer settings and uploaded it in google drive here: https://drive.google.com/file/d/1lBWUqF4TONyP7zY7dU51Fbz28lLJGw1P/view?usp=sharing
I hope finally you could fix this bug because I'm very loyal to your keyboard 
@menny

**Comment by CyanusBird** [comment]
After Last beta update "1.11.108" and the API level 15 upgrade the problem has been solved
Thanks @menny

**Comment by menny** [comment]
Thanks for reporting back. How long have you been using the new beta?

**Comment by CyanusBird** [comment]
I think since 20 september up until now, I waited all this time so if there would be any crashes but luckily there wasn't through the last 10 or 11 days so I came back to gave you my feedback after all this time ❤

**Comment by CyanusBird** [comment]
It now displays "on channel Error" with the same old issue

**Comment by menny** [comment]
I'm closing this issue, as this has not come up again, and we included a few fixes in the area.
