### ISSUE TITLE
Change default long press key for e, u, i, o, p

### ISSUE THREAD

**Issue by craftyguy** [AnySoftKeyboard/AnySoftKeyboard#707]
### Steps to reproduce
1. Long press on e, u, i, o, or, p
2. Popup menu comes up, and non-numerical key is selected by default
### Expected behaviour

the default selected key should be a number (e.g. e should be 3 and not ³)
### Actual behaviour

the default selected key is not what you would expect based on the tiny alternate key in the keyboard layout

**Android OS version:**
CyanogenMod  13

**Device manufacturer and model:**
Motor X 2014
**List of installed add-ons (like languages, or themes):**
English, light theme
![screenshot_20160915-135247](https://cloud.githubusercontent.com/assets/1474209/18567365/ac9888fa-7b4c-11e6-8d28-9673b1016f47.png)

**Comment by Tony-il-Capo** [comment]
Pretty much the same as [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/712)
Should be fixed now on beta, needs testing

**Comment by craftyguy** [comment]
I would totally test this if I could get the beta. I don't use Google Play, so unless there's a way to get it through F-droid or get the apk directly, I guess I'll have to wait to test it until it's "officially" released as a non-beta.

**Comment by lindhe** [comment]
Do you think this could be implemented in a global manner? Right now it seems to be up to whoever makes the keyboard layout, so the Swedish layout for example does not get a number row at all when long pressing the top row. :/ If it was a global setting maybe it could offload the not so active developers of alternative layouts.

**Comment by lindhe** [comment]
As already mentioned, I've got this problem with the Swedish keyboard too.

The string `1234567890` written with the top row is `12³456ùìò¶`, which is not very useful.

@friesenkiwi are you maintainer for that keyboard, or did you only take it on you to move it from the old repo in that other issue? If so: consider fixing it? If not: who is?

**Comment by friesenkiwi** [comment]
@lindhe, sorry, now I am not a maintainer of any of the ASK apps or packs, I just volunteered to resurrect the old SVN sources of several keyboard/language packs and I'm still in the process of doing it. This issue should be fixed globally for the default of all keyboards, and as this and the other thread looks to me, it already is?!
One could overwrite the default in each keyboard (e.g. the Swedish), but that would be a tedious task.
So sorry, can't help here :-(

**Comment by menny** [comment]
@lindhe it happens in Swedish pack only? English works as expected?

**Comment by lindhe** [comment]
No, you are right. English works the exact same way. No idea why it didn't come to mind to try that before posting.

**Comment by menny** [comment]
So, it's just a bug with Swedish?
Which Language pack are you using?

**Comment by Tony-il-Capo** [comment]
I'm using latest version from F-Droid (1.8-r8), I still have this problem for long press keys
>The string 1234567890 written with the top row is 12³456ùìò¶, which is not very useful.

This, i.e using default _"English QWERTY keyboard with symbols on long press"_ and _"Lean Dark Theme option 2"_, both  come with Anysoftkeyboard package.
Again, the string on top row keyboard is "1234567890", what it gets written is "12³456ùìò¶"

**Comment by menny** [comment]
Got it. Will fix this for the upcoming release

**Comment by menny** [comment]
The fix will be available in the next beta.

**Comment by papjul** [comment]
Why were there a need for re-align?
I don't want pop-ups to randomly change with new versions because keyboards in Language Packs would also need to be re-aligned. I give a lot of importance to the position of letters on long press so the most common ones from your language are accessible near your finger to reduce fingers movements. I don't want to lose time on my language pack because a new version would change the behaviour of long press so I need to be sure it will not change every month or so. Can how the popup appear be predictable?
Thanks in advance,

**Comment by friesenkiwi** [comment]
Well, it was only the order of characters in the default keyboard changed to provide a more consistent behaviour (see https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/5713fd172cbca3c232d905b6ef7fe4fdd01d9ce5), so nothing will change or would need to be re-aligned in a custom pack. And you yourself said 
> the popup should start on top of Q key to have the "3" first to be selected

in https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/712#issuecomment-269863872 ? :)

**Comment by papjul** [comment]
Yes, the re-alignment suggests that before some unknown commit, the popup would begin on top of Q key. Why was it changed? Is it sure that it will not change again in the near future?
I may look inquiring but I want the best design for my custom keyboards :)

**Comment by friesenkiwi** [comment]
No, I think that might be as misunderstanding. The programmatic behaviour of the pop-up was not changed in this issue. There is only one commit, and it is not unknown but https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/5713fd172cbca3c232d905b6ef7fe4fdd01d9ce5 and this commit only changed the order of characters (via `android:popupCharacters=""`) **in** some of the pop-ups of keys of the first row in the default English keyboard,  which are most probably overwritten anyway by your French keyboards. So no need to worry :-)

**Comment by menny** [comment]
yes, what @friesenkiwi said :)
