### ISSUE TITLE
First selected Long press (extra) keys do not match preview

### ISSUE THREAD

**Issue by Tony-il-Capo** [AnySoftKeyboard/AnySoftKeyboard#712]
Hi
### Steps to reproduce
1. Select QWERTY keyboard with extra symbols (extra characters when long pressing the keys) 
2. Select Simple Black Glow theme
### Expected behavior

The small character on keys should be the default when you long press and release the key
### Actual behavior

The default character (long press) that gets written does not not correspond to the one printed on key.
Example: key letter "i" have an small "8" (extra key), but if you long press it and then release it's not number "8" that gets written. Almost any key has multiple extra keys when long pressing them, but the one show on keyboard should match the one that is the FIRST to get selected (/written). This is very confusing when writing.

**Android OS version:**
4.1.2 (latest stock rom)

**Device manufacturer and model:**
Sony Xperia S (aka Lt26i)

**List of installed add-ons (like languages, or themes):**
Just default package from F-Droid.

**Comment by menny** [comment]
The fix should be available in the next beta release. Please sign up and ensure it is fixed.

**Comment by Tony-il-Capo** [comment]
A I understand it, beta releases are on gplay only, as I don't use google services, I will wait for the F-Droid release.

**Comment by menny** [comment]
very well. Let me know.

**Comment by Tony-il-Capo** [comment]
Hi
Shouldn't F-Droid version 1.8.329 have this fixed already? I've tested it and it have the same problem described above.

**Comment by papjul** [comment]
I can confirm, issue still here with build 438 compiled from branch gesture-typing.
See screenshot on #707, the popup should start on top of Q key to have the "3" first to be selected.
I'm trying to design a keyboard layout and I need this issue to be fixed to arrange popup keys.
